<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.fchen_group.Scf</groupId>
    <artifactId>TPDSInSCF</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.encoding>UTF-8</maven.compiler.encoding>
        <java.version>1.8</java.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <repositories>
        <repository>
            <id>nexus-tencentyun</id>
            <name>Nexus tencentyun</name>
            <url>https://mirrors.tencent.com/nexus/repository/maven-public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.73</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>development-Ten</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                    <version>2.9.3</version>
                </dependency>
                <dependency>
                    <groupId>com.qcloud</groupId>
                    <artifactId>cos_api</artifactId>
                    <version>5.6.35</version>
                </dependency>
                <dependency>
                    <groupId>com.tencentcloudapi</groupId>
                    <artifactId>scf-java-events</artifactId>
                    <version>0.0.1</version>
                </dependency>
                <dependency>
                    <groupId>com.tencentcloudapi</groupId>
                    <artifactId>tencentcloud-sdk-java</artifactId>
                    <version>3.1.1013</version>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>development-Ali</id>
            <dependencies>
                <dependency>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                    <version>2.9.3</version>
                </dependency>
                <!-- Tencent SDKs (needed to compile existing Tencent code) -->
                <dependency>
                    <groupId>com.qcloud</groupId>
                    <artifactId>cos_api</artifactId>
                    <version>5.6.35</version>
                </dependency>
                <dependency>
                    <groupId>com.tencentcloudapi</groupId>
                    <artifactId>scf-java-events</artifactId>
                    <version>0.0.1</version>
                </dependency>
                <dependency>
                    <groupId>com.tencentcloudapi</groupId>
                    <artifactId>tencentcloud-sdk-java</artifactId>
                    <version>3.1.1013</version>
                </dependency>
                <!-- Alibaba SDKs -->
                <dependency>
                    <groupId>com.aliyun.oss</groupId>
                    <artifactId>aliyun-sdk-oss</artifactId>
                    <version>3.17.4</version>
                </dependency>
                <dependency>
                    <groupId>com.aliyun</groupId>
                    <artifactId>fc20230330</artifactId>
                    <version>4.1.2</version>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>production-Ali</id>
            <dependencies>
                <dependency>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                    <version>2.9.3</version>
                </dependency>
                <dependency>
                    <groupId>com.aliyun.oss</groupId>
                    <artifactId>aliyun-sdk-oss</artifactId>
                    <version>3.17.4</version>
                </dependency>
                <dependency>
                    <groupId>com.aliyun</groupId>
                    <artifactId>fc20230330</artifactId>
                    <version>4.1.2</version>
                    <scope>provided</scope>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>production-Ten</id>
            <dependencies>
                <dependency>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                    <version>2.9.3</version>
                </dependency>
                <dependency>
                    <groupId>com.qcloud</groupId>
                    <artifactId>cos_api</artifactId>
                    <version>5.6.35</version>
                </dependency>
                <dependency>
                    <groupId>com.tencentcloudapi</groupId>
                    <artifactId>scf-java-events</artifactId>
                    <version>0.0.1</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.tencentcloudapi</groupId>
                    <artifactId>tencentcloud-sdk-java</artifactId>
                    <version>3.1.1013</version>
                    <scope>provided</scope>
                </dependency>
            </dependencies>
        </profile>



        <profile>
            <id>development-AWS</id>
            <dependencies>
                <dependency>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                    <version>2.9.3</version>
                </dependency>
                <!-- Tencent SDKs -->
                <dependency>
                    <groupId>com.qcloud</groupId>
                    <artifactId>cos_api</artifactId>
                    <version>5.6.35</version>
                </dependency>
                <dependency>
                    <groupId>com.tencentcloudapi</groupId>
                    <artifactId>scf-java-events</artifactId>
                    <version>0.0.1</version>
                </dependency>
                <dependency>
                    <groupId>com.tencentcloudapi</groupId>
                    <artifactId>tencentcloud-sdk-java</artifactId>
                    <version>3.1.1013</version>
                </dependency>
                <!-- Alibaba SDKs -->
                <dependency>
                    <groupId>com.aliyun.oss</groupId>
                    <artifactId>aliyun-sdk-oss</artifactId>
                    <version>3.17.4</version>
                </dependency>
                <dependency>
                    <groupId>com.aliyun</groupId>
                    <artifactId>fc20230330</artifactId>
                    <version>4.1.2</version>
                </dependency>
                <!-- AWS SDKs -->
                <dependency>
                    <groupId>com.amazonaws</groupId>
                    <artifactId>aws-java-sdk-s3</artifactId>
                    <version>1.12.770</version>
                </dependency>
                <dependency>
                    <groupId>com.amazonaws</groupId>
                    <artifactId>aws-lambda-java-core</artifactId>
                    <version>1.2.3</version>
                </dependency>
                <dependency>
                    <groupId>com.amazonaws</groupId>
                    <artifactId>aws-java-sdk-lambda</artifactId>
                    <version>1.12.770</version>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>production-AWS</id>
            <dependencies>
                <dependency>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                    <version>2.9.3</version>
                </dependency>
                <dependency>
                    <groupId>com.amazonaws</groupId>
                    <artifactId>aws-java-sdk-s3</artifactId>
                    <version>1.12.770</version>
                </dependency>
                <dependency>
                    <groupId>com.amazonaws</groupId>
                    <artifactId>aws-lambda-java-core</artifactId>
                    <version>1.2.3</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.amazonaws</groupId>
                    <artifactId>aws-java-sdk-lambda</artifactId>
                    <version>1.12.770</version>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>development-Azure</id>
            <dependencies>
                <dependency>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                    <version>2.13.5</version>
                </dependency>
                <dependency>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-core</artifactId>
                    <version>2.13.5</version>
                </dependency>
                <dependency>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                    <version>2.13.5</version>
                </dependency>
                <dependency>
                    <groupId>com.fasterxml.jackson.dataformat</groupId>
                    <artifactId>jackson-dataformat-xml</artifactId>
                    <version>2.13.5</version>
                </dependency>
                <dependency>
                    <groupId>com.fasterxml.jackson.datatype</groupId>
                    <artifactId>jackson-datatype-jsr310</artifactId>
                    <version>2.13.5</version>
                </dependency>
                <!-- Tencent SDKs -->
                <dependency>
                    <groupId>com.qcloud</groupId>
                    <artifactId>cos_api</artifactId>
                    <version>5.6.35</version>
                </dependency>
                <dependency>
                    <groupId>com.tencentcloudapi</groupId>
                    <artifactId>scf-java-events</artifactId>
                    <version>0.0.1</version>
                </dependency>
                <dependency>
                    <groupId>com.tencentcloudapi</groupId>
                    <artifactId>tencentcloud-sdk-java</artifactId>
                    <version>3.1.1013</version>
                </dependency>
                <!-- Alibaba SDKs -->
                <dependency>
                    <groupId>com.aliyun.oss</groupId>
                    <artifactId>aliyun-sdk-oss</artifactId>
                    <version>3.17.4</version>
                </dependency>
                <dependency>
                    <groupId>com.aliyun</groupId>
                    <artifactId>fc20230330</artifactId>
                    <version>4.1.2</version>
                </dependency>
                <!-- AWS SDKs -->
                <dependency>
                    <groupId>com.amazonaws</groupId>
                    <artifactId>aws-java-sdk-s3</artifactId>
                    <version>1.12.770</version>
                </dependency>
                <dependency>
                    <groupId>com.amazonaws</groupId>
                    <artifactId>aws-lambda-java-core</artifactId>
                    <version>1.2.3</version>
                </dependency>
                <dependency>
                    <groupId>com.amazonaws</groupId>
                    <artifactId>aws-java-sdk-lambda</artifactId>
                    <version>1.12.770</version>
                </dependency>
                <!-- Azure SDKs -->
                <dependency>
                    <groupId>com.azure</groupId>
                    <artifactId>azure-storage-blob</artifactId>
                    <version>12.25.0</version>
                </dependency>
                <dependency>
                    <groupId>com.microsoft.azure.functions</groupId>
                    <artifactId>azure-functions-java-library</artifactId>
                    <version>2.2.0</version>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.microsoft.azure</groupId>
                        <artifactId>azure-functions-maven-plugin</artifactId>
                        <version>1.30.0</version>
                        <configuration>
                            <appName>audit-test-azure</appName>
                            <resourceGroup>scf-audit-rg</resourceGroup>
                            <region>japanwest</region>
                            <appServicePlanName>ASP-scfauditrg-89ce</appServicePlanName>
                            <runtime>
                                <os>windows</os>
                                <javaVersion>11</javaVersion>
                            </runtime>
                            <appSettings>
                                <property>
                                    <name>FUNCTIONS_EXTENSION_VERSION</name>
                                    <value>~4</value>
                                </property>
                            </appSettings>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>production-Azure</id>
            <dependencies>
                <dependency>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                    <version>2.13.5</version>
                </dependency>
                <dependency>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-core</artifactId>
                    <version>2.13.5</version>
                </dependency>
                <dependency>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                    <version>2.13.5</version>
                </dependency>
                <dependency>
                    <groupId>com.fasterxml.jackson.dataformat</groupId>
                    <artifactId>jackson-dataformat-xml</artifactId>
                    <version>2.13.5</version>
                </dependency>
                <dependency>
                    <groupId>com.fasterxml.jackson.datatype</groupId>
                    <artifactId>jackson-datatype-jsr310</artifactId>
                    <version>2.13.5</version>
                </dependency>
                <dependency>
                    <groupId>com.azure</groupId>
                    <artifactId>azure-storage-blob</artifactId>
                    <version>12.25.0</version>
                </dependency>
                <dependency>
                    <groupId>com.microsoft.azure.functions</groupId>
                    <artifactId>azure-functions-java-library</artifactId>
                    <version>2.2.0</version>
                    <scope>provided</scope>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.microsoft.azure</groupId>
                        <artifactId>azure-functions-maven-plugin</artifactId>
                        <version>1.30.0</version>
                        <configuration>
                            <appName>audit-test-azure</appName>
                            <resourceGroup>scf-audit-rg</resourceGroup>
                            <region>japanwest</region>
                            <appServicePlanName>ASP-scfauditrg-89ce</appServicePlanName>
                            <runtime>
                                <os>windows</os>
                                <javaVersion>11</javaVersion>
                            </runtime>
                            <appSettings>
                                <property>
                                    <name>FUNCTIONS_EXTENSION_VERSION</name>
                                    <value>~4</value>
                                </property>
                            </appSettings>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <mainClass>com.fchen_group.TPDSInScf.Run.Benchmark</mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <id>Audit_Benchmark</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <finalName>${project.build.finalName}_Benchmark</finalName>
                            <archive>
                                <manifest>
                                    <addClasspath>true</addClasspath>
                                    <mainClass>com.fchen_group.TPDSInScf.Run.Benchmark</mainClass>
                                </manifest>
                            </archive>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
